# Generated by Django 6.1.1 on 2026-09-29 02:00

import datetime
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_partner_and_testimonial_snippets'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'news categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('introduction', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Post date')),
                ('introduction', models.TextField(max_length=300)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('quote', 8), ('call_to_action', 14), ('impact_stats', 18), ('embed', 19), ('table', 20), ('document', 23), ('testimonial', 24), ('partners', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'document-link', 'ol', 'ul'], 'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('text', 7), ('attribution', 5)]], {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.TextBlock', (), {'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Donate'}), 12: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Link to a page on this site…', 'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'help_text': '…or to an external address.', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 10), ('button_text', 11), ('page', 12), ('url', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 12,000 or 95%'}), 16: ('wagtail.blocks.StructBlock', [[('figure', 15), ('label', 9)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'max_num': 4, 'min_num': 1}), 18: ('wagtail.blocks.StructBlock', [[('heading', 5), ('stats', 17)]], {}), 19: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'A YouTube or Vimeo link', 'icon': 'media'}), 20: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 21: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Defaults to the document title.', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('document', 21), ('link_text', 22)]], {}), 24: ('core.blocks.TestimonialBlock', (), {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Our partners', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('heading', 25)]], {})})),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='news.newscategory')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='news.newspage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newspage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.NewsPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
