# Generated by Django 6.1.1 on 2026-09-29 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner_and_testimonial_snippets'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='social_image',
            field=models.ForeignKey(blank=True, help_text='Shown when the page is shared on social media. Defaults to the main image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage'),
        ),
    ]
