# Generated by Django 6.1.1 on 2026-10-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_editor_and_moderator_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(choices=[('NPR', 'Nepalese rupee (Rs)'), ('GBP', 'Pound sterling (£)')], default='NPR', help_text='Shown with every amount on the site, such as appeal targets and gifts.', max_length=3),
        ),
    ]
