# Generated by Django 6.1.1 on 2026-10-05 07:27

import core.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone_country',
            field=models.CharField(choices=core.phone.phone_country_choices, default='NP', help_text='The country selected by default for phone numbers on forms.', max_length=2),
        ),
    ]
