# Generated by Django 6.1.1 on 2026-10-07 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_translation_permissions'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_page',
            field=models.ForeignKey(blank=True, help_text="Says how supporters' details are used. Linked from the footer and next to every form's send button, once it's published.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='privacy notice'),
        ),
    ]
