# Generated by Django 6.1.1 on 2026-10-09 21:18

import core.brand
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_text_in_each_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_colour',
            field=models.CharField(default='#f2b134', help_text='The Donate button and other main buttons, progress bars and the announcement banner. The text on it is dark or white, whichever is easier to read.', max_length=7, validators=[core.brand.validate_accent_colour]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_colour',
            field=models.CharField(default='#0b5563', help_text='Links and outlined buttons, and in a darker shade headings, the name bar at the top and the footer. White text goes on it, so it must be dark enough to read.', max_length=7, validators=[core.brand.validate_main_colour]),
        ),
    ]
