# Generated by Django 6.1.1 on 2026-10-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_brand_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_style',
            field=models.CharField(choices=[('dark', 'Dark, with white text'), ('light', 'Light, with dark text')], default='dark', help_text="Your charity's details at the bottom of every page.", max_length=5, verbose_name='footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='name_bar_style',
            field=models.CharField(choices=[('dark', 'Dark, with white text'), ('light', 'Light, with dark text')], default='dark', help_text="The row with your charity's name at the top of every page.", max_length=5, verbose_name='name bar'),
        ),
    ]
