# Generated by Django 6.1.1 on 2026-10-10 06:57

import core.brand
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_name_bar_and_footer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_style',
            field=models.CharField(choices=[('dark', "Dark: your main colour's dark shade, with pale text and white links"), ('light', 'Light: a pale tint of your main colour, with dark text and links in your main colour')], default='dark', help_text="Your charity's details at the bottom of every page.", max_length=5, verbose_name='footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='main_colour',
            field=models.CharField(default='#0b5563', help_text="Links and outlined buttons, and in a darker shade headings and, when they're dark, the name bar at the top and the footer. White text goes on it, so it must be dark enough to read.", max_length=7, validators=[core.brand.validate_main_colour]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name_bar_style',
            field=models.CharField(choices=[('dark', "Dark: your main colour's dark shade, with the name in white"), ('light', 'Light: white, with the name in a dark shade of your main colour')], default='dark', help_text="The row with your charity's name at the top of every page.", max_length=5, verbose_name='name bar'),
        ),
    ]
