# Generated by Django 6.1.1 on 2026-10-10 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_name_bar_and_footer_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text="Shown beside your charity's name at the top of every page. A PNG with a transparent background, about as wide as it is tall, works best. If it's drawn for a white background, choose a light name bar below.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage'),
        ),
    ]
