# Generated by Django 6.1.1 on 2026-10-10 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_size',
            field=models.PositiveSmallIntegerField(default=80, help_text="How tall the logo is on a phone, from the smallest to the largest, in pixels. On a wide screen it's a little taller. Open the preview with the phone icon at the top right to see it on the site's pages before you save.", validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
