# Generated by Django 6.1.1 on 2026-09-29 01:58

import datetime
import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_partner_and_testimonial_snippets'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('introduction', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CampaignPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('summary', models.TextField(help_text='Shown on listing cards and in search.', max_length=300)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('quote', 8), ('call_to_action', 14), ('impact_stats', 18), ('embed', 19), ('table', 20), ('document', 23), ('testimonial', 24), ('partners', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'document-link', 'ol', 'ul'], 'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('text', 7), ('attribution', 5)]], {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.TextBlock', (), {'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Donate'}), 12: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Link to a page on this site…', 'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'help_text': '…or to an external address.', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 10), ('button_text', 11), ('page', 12), ('url', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 12,000 or 95%'}), 16: ('wagtail.blocks.StructBlock', [[('figure', 15), ('label', 9)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'max_num': 4, 'min_num': 1}), 18: ('wagtail.blocks.StructBlock', [[('heading', 5), ('stats', 17)]], {}), 19: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'A YouTube or Vimeo link', 'icon': 'media'}), 20: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 21: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Defaults to the document title.', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('document', 21), ('link_text', 22)]], {}), 24: ('core.blocks.TestimonialBlock', (), {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Our partners', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('heading', 25)]], {})})),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_raised', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing appeals.', null=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DonationAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('amount', models.PositiveIntegerField(help_text='In pounds.')),
                ('impact', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_amounts', to='campaigns.campaignpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
