# Generated by Django 6.1.1 on 2026-10-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_highlight_rich_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationamount',
            name='amount',
            field=models.PositiveIntegerField(help_text="A whole amount in the site's currency."),
        ),
    ]
