# Generated by Django 6.1.1 on 2026-10-05 14:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_amount_in_site_currency'),
        ('core', '0006_sitesettings_phone_country'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('introduction', models.TextField(blank=True)),
                ('payment_notice', wagtail.fields.RichTextField(default="<p>No payment is taken on this website yet. Send this form and we'll contact you about how to pay. If you choose monthly, we'll help you set up a regular payment.</p>", help_text='Shown above the form: say plainly how payment works and what happens next.')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('quote', 8), ('call_to_action', 14), ('impact_stats', 18), ('embed', 19), ('table', 20), ('document', 23), ('testimonial', 24), ('partners', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'mark', 'link', 'document-link', 'ol', 'ul'], 'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('text', 7), ('attribution', 5)]], {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.TextBlock', (), {'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Donate'}), 12: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Link to a page on this site…', 'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'help_text': '…or to an external address.', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 10), ('button_text', 11), ('page', 12), ('url', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 12,000 or 95%'}), 16: ('wagtail.blocks.StructBlock', [[('figure', 15), ('label', 9)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'max_num': 4, 'min_num': 1}), 18: ('wagtail.blocks.StructBlock', [[('heading', 5), ('stats', 17)]], {}), 19: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'A YouTube or Vimeo link', 'icon': 'media'}), 20: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 21: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Defaults to the document title.', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('document', 21), ('link_text', 22)]], {}), 24: ('core.blocks.TestimonialBlock', (), {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Our partners', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('heading', 25)]], {})}, help_text='Shown below the form, e.g. a table of where the money goes.')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Shown after someone sends the form.')),
                ('social_image', models.ForeignKey(blank=True, help_text='Shown when the page is shared on social media. Defaults to the main image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DonatePageAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('amount', models.PositiveIntegerField(help_text="A whole amount in the site's currency.")),
                ('impact', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_amounts', to='campaigns.donatepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text="A whole amount in the pledge's currency.")),
                ('currency', models.CharField(choices=[('NPR', 'Nepalese rupee (Rs)'), ('GBP', 'Pound sterling (£)')], max_length=3)),
                ('frequency', models.CharField(choices=[('one-off', 'One-off'), ('monthly', 'Monthly')], default='one-off', max_length=7, verbose_name='how often')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, help_text='In international form (+9779841234567). Monthly pledges only, for the reminder.', max_length=16, verbose_name='mobile number')),
                ('address', models.TextField(blank=True, help_text='House or ward number, street or tole, town or municipality, district.')),
                ('postcode', models.CharField(blank=True, max_length=12, verbose_name='postcode or postal code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='sent')),
                ('appeal', models.ForeignKey(blank=True, help_text="Blank means wherever it's needed most.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to='campaigns.campaignpage')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to='campaigns.donatepage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
