# Generated by Django 6.1.1 on 2026-10-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_pledge_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='email_updates',
            field=models.BooleanField(default=False, help_text='Agreed to emails about our projects and appeals.'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='message',
            field=models.TextField(blank=True, help_text='For the team only; never shown on the site.', max_length=1000),
        ),
        migrations.AddField(
            model_name='pledge',
            name='show_on_website',
            field=models.BooleanField(default=False, help_text='Agreed to their name, amount, appeal and date being listed once received.'),
        ),
    ]
