# Generated by Django 6.1.1 on 2026-10-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_pledge_message_and_consents'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='submission_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
